# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Main workflow

on:
  push:
    branches: [ "initial-phase" ]
  pull_request:
    branches: [ "main" ]

jobs:
#  call-reusable-workflow:
#    if: ${{ github.event_name=='push' && github.ref == 'refs/heads/initial-phase'}}
#    uses: ./.github/workflows/reusable_workflow.yml
#    ## with some input
  steps:
    - name: Run a job
      id: init-print
      run: |
        echo "Running main workflow"

    - name: Determine condition
      id: determine_condition
      run: |
        # Example condition: Set condition based on some logic
        if [ "${{ github.ref }}" == "refs/heads/main" ]; then
          echo "condition=true" >> $GITHUB_ENV
        else
          echo "condition=false" >> $GITHUB_ENV
        fi
    - name: Trigger secondary workflow
      if: env.condition == 'true'
      run: |
        curl -X POST \
        -H "Authorization: token ${{ secrets.GH_WF_TOKEN }}" \
        -H "Accept: application/vnd.github.v3+json" \
        -d '{"event_type": "trigger-secondary-workflow", "client_payload": {"ref": "${{ github.ref }}"}}' \
        https://api.github.com/repos/${{ github.repository }}/dispatches
